# permissions for end users to view quickbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: quickbuild-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: quickbuild
    app.kubernetes.io/part-of: quickbuild
    app.kubernetes.io/managed-by: kustomize
  name: quickbuild-viewer-role
rules:
- apiGroups:
  - app.mark8s.io
  resources:
  - quickbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.mark8s.io
  resources:
  - quickbuilds/status
  verbs:
  - get
