apiVersion: v1
kind: Service
metadata:
  name: {{.Spec.Name }}
  namespace: {{.Spec.Namespace}}
spec:
  selector:
    app: {{ .Spec.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Spec.Port }}
      targetPort: {{ .Spec.Port }}


